#MS port number
server.port=8082

#service instance name
spring.application.name=Billing-Service

#URL to register the MS with eureka server
eureka.client.service-url.default.zone=http://localhost:8761//eureka

#isntanceId
eureka.instance.instance-id=${spring.application.name}:${random.value}

#log file name
logging.file.name=d:/billing_elk_log1.txt

#logger level
logging.level.com.nt=info
logging.level.org.springframework=off