spring.application.name=BootMsProj01-R-DServer-EurekaServer

#Eureka server port number
server.port=8761

#Make this project as eureka server by disabling registry and fetch operations
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false