#MS Port Number
server.port=6062

#MS application name /server instance id
spring.application.name=Customer-Service

#url to register with eureka server
eureka.client.service-url.default-zone=http://localhost:8761/eureka

#url to connect with config server by making the ms config client
#Below is used when default port of config server is 8888 or else we need to write complete url of config server(if it is 8839 eg: then it will be 
#spring.config.import=optional:configserver:http://localhost:8839)
spring.config.import=optional:configserver:

#activate the springboot actuators (either all * or only refresh) for refresh scope
management.endpoints.web.exposure.include=*