spring.application.name=Amazon-API-Gateway

server.port=8888


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#These code is commented becuase the flow is from Gateway->service registry(eureka server)->MS
# User Service
#spring.cloud.gateway.server.webflux.routes[0].id=Amazon-User-Service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8001
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1  #removed in case of request mapping if we use request mapping this no need

# Order Service
#spring.cloud.gateway.server.webflux.routes[1].id=Amazon-Order-Service
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8002
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1  #removed in case of request mapping if we use request mapping this no need

# Payment Service
#spring.cloud.gateway.server.webflux.routes[2].id=Amazon-Payment-Service
#spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8003
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payment/**
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1 #removed in case of request mapping if we use request mapping this no need

#this is important to enable api gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#By default we will pass service-id as upper case only eg: http://localhost:8888/AMAZON-ORDER-SERVICE/order/info/1,http://localhost:8888/AMAZON-USER-SERVICE/user/create
#to enable lower case
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

