#config server port
server.port=8888

#By default in config server getting from external source like git lab will be active to overcome that we use spring.profiles.active=native
#Activate the native profile to deal with native config file
spring.profiles.active=native

#Natvie config file link url
spring.cloud.config.server.native.search-locations=classpath:/config