#Ms port number
server.port=4041

#service instance name
spring.application.name=Shopping-Service

#register with EurekaServer
eureka.client.service-url.default-zone=http://localhost:8761//eureka

#log file name
logging.file.name=d:/shopping_elk_log3.txt

#logger level
logging.level.com.nt=info